
import './globals.css'
import { AuthProvider } from '@/context/Providers';
import { ReactNode } from 'react';
import { Toaster } from "react-hot-toast";


export const metadata = {
  title: 'PreviApp ',
  description: 'Generated by create next app',
}
// Define la interfaz para las propiedades del componente
interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout = ({ children }:RootLayoutProps) => {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <div>
            <Toaster position="bottom-center" />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}


export default RootLayout;